### ISSUE TITLE
installing along sdk breaks mod support

### ISSUE THREAD

**Issue by NeosGhost** [apple1417/bl2-scroll-macro#1]
would it be possible to get this so that i can use it alongside your other sdk mods?

**Comment by apple1417** [comment]
This is mostly deliberate. Mods aren't allowed in runs, and the old sdk actually crashes on 1.1, so by proxying the same file it forces people to get rid of it.

There's no good way to make this compatible with the old sdk, since both versions need to hook the same functions in the game, and once one dll does the other cannot. Once the mod manager is rewritten to use the new sdk, the same one this project uses, then it will be possible, since the new sdk can be set up to do all the hooking in a single `unrealsdk.dll`, which multiple different dlls can call into. Once this happens, I don't think I'll do an explicit release for the same reasons as above, but you should be able to compile one yourself by configuring with `-DUNREALSDK_SHARED=True`.

**Comment by NeosGhost** [comment]
thx apple
